### ISSUE TITLE
Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.

### ISSUE THREAD

**Issue by mishushakov** [actions-on-google/assistant-actions-nodejs#2]
Sample code

```js
const {ActionsSdkClient} = require('@assistant/actions')

const client = new ActionsSdkClient({
  parent: 'projects/action-builder-test-40291'
})

client.listVersions({parent: 'projects/action-builder-test-40291'}).then(version => console.log)
```

Log

```
mish@ushakov action-builder-test % node index.js
(node:39636) UnhandledPromiseRejectionWarning: Error: 9 FAILED_PRECONDITION: Firebase Terms of Service is not accepted. Navigate to your project's overview page on the Actions Console to accept the Terms of Service.
    at Object.callErrorFromStatus (/Users/mish/Downloads/action-builder-test/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/Users/mish/Downloads/action-builder-test/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/Users/mish/Downloads/action-builder-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/Users/mish/Downloads/action-builder-test/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /Users/mish/Downloads/action-builder-test/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

don't see anything on the overview page, adblocker disabled

<img width="1680" alt="Screenshot 2021-04-21 at 15 59 59" src="https://user-images.githubusercontent.com/10400064/115566582-a6bdb780-a2ba-11eb-8da1-afd600e8e379.png">

**Comment by mishushakov** [comment]
making a firebase project first then creating action - didn't help

**Comment by atulep** [comment]
Thank you for including all of the details. Can you confirm if you're using service account for authentication (similar to [this](https://github.com/actions-on-google/assistant-conversation-testing-nodejs#setup) setup)?

**Comment by mishushakov** [comment]
@atulep yes
also, if i try to directly make a HTTP request to Actions API i would get a 403, insufficient permission error
my service account has Actions Admin and Actions Viewer permissions and the Actions API is enabled on project

**Comment by mishushakov** [comment]
yes, i'm using service account with Actions Admin and Actions Viewer permissions
my project has Actions API enabled

i also noticed when i try to make a HTTP directly through `google-auth-library` client i'm getting a 403: Insufficient Permissions

i'm not sure i'm doing everything right and the Actions API documentation does not give any hint whatsoever when it comes to authentication and required scopes

**Comment by atulep** [comment]
The Terms of Service error has to do with the bug in the API. ToS acceptance window would normally show up if you call API with your credentials, for example, when you use gactions CLI. However, it behaves incorrectly when API is called with service accounts. We rolled out a fix for this, which should be take effect soon. 

Regarding insufficient permissions, try adding `https://www.googleapis.com/auth/actions.builder` scope. I'd also suggest looking at [gactions](https://github.com/actions-on-google/gactions/blob/master/api/apiutils.go#L44) implementation for some pointers.

**Comment by mishushakov** [comment]
thanks a lot, the code seems to be working correctly now!
